module.exports = {
  entry: [
    "./public/js/alerts.js",
    "./public/js/autoClick.js",
    "./public/js/avgrund.js",
    "./public/js/dashboard.js",
    "./public/js/hoverable-collapse.js",
    "./public/js/template.js",
    "./public/js/main.js",
    "./public/js/off-canvas.js",
    "./public/js/settings.js",
    "./public/js/jquery.gracket.min.js",
    "./public/js/jquery.form.js",
    "./public/js/jquery.challonge.js",
    "./public/js/todolist.js",
    "./public/js/wizard.js",
    "./public/js/bootstrap.min.js",
    "./public/js/contactform.js",
    "./public/js/jquery.js",
    "./public/js/masonry.js",
    "./public/js/modernizr.min.js",
    "./public/js/particles.js",
    "./public/js/popper.min.js",
    "./public/js/stellar.js",
    "./public/js/stickysidebar.js",
    ".public/js/bundle-addons.js",
    ".public/js/bundle-base.js",
  ],
  output: {
    path: __dirname + "/dist/",
    filename: "bundle.js",
    publicPath: "/",
  },
  devServer: {
    inline: false,
    contentBase: "./dist",
  },
};
